name: CI
on: [push, pull_request]

concurrency: 
  group: ci
  cancel-in-progress: true
    
jobs:
    macOS_11:
        name: Test macOS 11
        runs-on: macOS-11
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2
            - name: macOS 11
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=macOS" clean test | xcpretty

    iOS_15:
        name: Test iOS 15
        runs-on: macOS-11
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2
            - name: iOS 15
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=iOS Simulator,name=iPhone 11,OS=15.0" clean test | xcpretty
    iOS_14:
        name: Test iOS 14
        runs-on: macOS-11
        env:
            DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2
            - name: iOS 14
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=iOS Simulator,name=iPhone 11,OS=14.4" clean test | xcpretty

    tvOS_15:
        name: Test tvOS 15
        runs-on: macOS-11
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2
            - name: tvOS 15
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=tvOS Simulator,name=Apple TV 4K (2nd generation),OS=15.0" clean test | xcpretty
    tvOS_14:
        name: Test tvOS 14
        runs-on: macOS-11
        env:
            DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2
            - name: tvOS 14
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=tvOS Simulator,name=Apple TV 4K,OS=14.3" clean test | xcpretty

    watchOS_8:
        name: Test watchOS 8
        runs-on: macOS-11
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2
            - name: watchOS 8.0
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=watchOS Simulator,name=Apple Watch Series 7 - 45mm,OS=8.0" clean test | xcpretty
